export { SkillHotError } from './errors.js'
export { createDiscoveryEngine, createInstallPrompt } from './discovery.js'
export { expandTerms, normalizeQuery, SYNONYMS } from './normalize.js'
export { parseCatalog } from './schema.js'
export { loadCatalog, loadCatalogWithMetadata, loadLiveCatalogWithMetadata, refreshCatalog, SKILLHOT_PUBLIC_CATALOG_URL } from './store.js'
export type { DiscoveryEngine, FindOptions, FindResult, InstallPrompt, MatchReason, Recommendation } from './discovery.js'
export type { CatalogMetadata, LiveCatalogOptions, LoadedCatalog, LoadCatalogOptions, RefreshOptions } from './store.js'
export type { Catalog, CatalogSkill, InstallCommandSource } from './types.js'
